Aw/ct 210
mxenabled/mx-design-tokens pull request #104
Opened 2024-01-12 18:27 UTC by ash-wright123

Changed the color of the focus ring to comply with ADA standards it will now have a 3:1 contrast ratio

2024-01-17 19:56 UTC, mwclemy requested changes

2024-01-17 19:56 UTC, mwclemy commented on CHANGELOG.md
> +## [1.0.3] - 01-12-2023
Nit: the year should be 2024 right? 😂

2024-01-17 19:57 UTC, ash-wright123 commented on CHANGELOG.md
> +## [1.0.3] - 01-12-2023
yes

2024-01-17 20:16 UTC, mwclemy requested changes

2024-01-17 20:16 UTC, mwclemy commented on src/core.ts
> +    Focus: '0px 0px 0px 2px rgba(45, 100, 239, 1)',
Shouldn't the opacity be 75%? I'm just reading from the attached issue.

Also if I convert `#095ADB` to rgb, I get `rgb(9, 90, 219)` and the rgba value would be `rgb(9, 90, 219, 0.75)`.

2024-01-17 20:21 UTC, ash-wright123 commented on src/core.ts
> +    Focus: '0px 0px 0px 2px rgba(45, 100, 239, 1)',
Good catch, I'm not sure why it converted to (45,100,239)

2024-01-18 00:14 UTC, mwclemy approved these changes

2024-01-18 00:14 UTC, mwclemy commented
LGTM! Thanks for the quick fix.

2024-01-18 19:31 UTC, merged